### PR TITLE
[W5.1a][W13-3]ChelseyOng

### PR DESCRIPTION
**Pull request by chel-seyy**
Extracted a new Formatter class from TextUI to follow SRP

### CODE REVIEW

**Review by Sri-vatsa — CHANGES_REQUESTED** [review]
Good that you attempted  👍 If you take a second look at your `Formatter` class you will realize that SRP is violated. `Formatter` is not only formatting the text but also displaying to a user. Think about how you can make this even better by splitting the two responsibilities.

**Comment by chel-seyy** [comment]
Ready for review

**Review by Sri-vatsa — APPROVED** [review]

**Comment by Sri-vatsa** [comment]
Awesome! Keep up the good work :)

**Comment by chel-seyy** [comment]
Thanks!

**Pull request closed without merging**
